"""fix user timestamps

Revision ID: 4dde84770b0f
Revises: b2a094f3f3db
Create Date: 2026-04-03 15:44:26.979765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dde84770b0f'
down_revision = 'b2a094f3f3db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
