"""init

Revision ID: b2a094f3f3db
Revises: 
Create Date: 2026-04-03 15:36:35.644129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2a094f3f3db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blocklist',
    sa.Column('jti', sa.String(length=255), nullable=False),
    sa.Column('token_type', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('financial_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('record_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_records_category'), 'financial_records', ['category'], unique=False)
    op.create_index(op.f('ix_financial_records_id'), 'financial_records', ['id'], unique=False)
    op.create_index(op.f('ix_financial_records_is_deleted'), 'financial_records', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_financial_records_record_date'), 'financial_records', ['record_date'], unique=False)
    op.create_index(op.f('ix_financial_records_record_type'), 'financial_records', ['record_type'], unique=False)
    op.create_index('ix_financial_records_user_date', 'financial_records', ['user_id', 'record_date'], unique=False)
    op.create_index(op.f('ix_financial_records_user_id'), 'financial_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_records_user_id'), table_name='financial_records')
    op.drop_index('ix_financial_records_user_date', table_name='financial_records')
    op.drop_index(op.f('ix_financial_records_record_type'), table_name='financial_records')
    op.drop_index(op.f('ix_financial_records_record_date'), table_name='financial_records')
    op.drop_index(op.f('ix_financial_records_is_deleted'), table_name='financial_records')
    op.drop_index(op.f('ix_financial_records_id'), table_name='financial_records')
    op.drop_index(op.f('ix_financial_records_category'), table_name='financial_records')
    op.drop_table('financial_records')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('token_blocklist')
    # ### end Alembic commands ###
